databases:
- name: exo1_serverless_bdd-3
  databaseName: exo1_serverless_bdd-3
  user: exo1_serverless_bdd_user
  plan: free
  region: oregon
  ipAllowList:
    - source: 0.0.0.0/0
      description: everywhere
  postgresMajorVersion: "16"

services:
  - type: web
    name: exo1_serverless-3
    runtime: node
    repo: https://github.com/ESGI-AL4/exo1_serverless
    plan: free
    envVars:
      - key: DB_URL
        sync: false
    region: oregon
    buildCommand: npm i
    startCommand: npm start
version: "1"
