services:
  - type: web
    name: bp-app
    runtime: node
    repo: https://github.com/ESGI-AL4/exo1_serverless
    buildCommand: npm i
    startCommand: npm start
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bp-db
          property: connectionString


databases:
- name: bp-db
  plan: free
  region: frankfurt


